on:
  pull_request:
    branches:
      - main
      - master

jobs:
  make_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make File
        run: sh deploy.sh ${{ github.head_ref }}

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0

