on:
  pull_request:
    branches:
      - main
      - master

jobs:
  make_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make File
        run: |
          BRANCH=$(echo ${{ github.head_ref }} | sed 's+/+-+g')
          cd .k8s && mkdir -p $BRANCH  && touch $BRANCH/index.js
