on:
  pull_request:
    types:
      - closed

jobs:
  remove_branch_manifests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0

      - name: Remove manifests
        shell: bash
        run: rm -rf $(echo ${{ github.head_ref }} | sed 's+/+-+g')